/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mathijs' at '9/3/15 10:47 AM' with Gradle 2.4
 *
 * @author mathijs, @date 9/3/15 10:47 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
